Hacker News
Chancellor-Arthur/hacker-news pull request #1
Opened 2022-07-27 16:27 UTC by Chancellor-Arthur

В проекте есть некоторые проблемы, у блока комментариев нет адаптивной верстки на странице новости, но это ненадолго, ждём патчей первого дня, в проекте есть два // @ts ignore - не смог договориться с типизацией, и кое-где стоит тип any, проблема аналогичная, особенно интересно с типизацией exception, нужны советы и помощь

Проект залит на heroku
codesandbox  - https://codesandbox.io/s/reverent-burnell-c4sxwl?file=/src/App.tsx

2022-07-27 19:27 UTC, crutch12 commented
отдал @stilwuc

2022-07-30 18:45 UTC, Chancellor-Arthur commented
heroku умер, время смерти - 21:45, реанимировать не получилось, смотрим на codesandbox

2022-08-02 13:56 UTC, Stilwuc requested changes

2022-08-02 13:56 UTC, Stilwuc commented on src/components/Loader.tsx
> +const Loader = () => {
Красивый лоадер 👍

2022-08-02 13:56 UTC, Stilwuc commented on src/components/PostItem.tsx
> +import {Box, Button, Card, CardActions, CardContent, Typography,} from "@mui/material";
запятая последняя выглядит опасно)
```suggestion
import {Box, Button, Card, CardActions, CardContent, Typography} from "@mui/material";
```

2022-08-02 13:56 UTC, Stilwuc commented on src/components/AppBar.tsx
> +interface Props {
Лучше называть `{ComponentName}Props`

2022-08-02 13:56 UTC, Stilwuc commented on src/pages/Posts.tsx
> +        setInterval(reloadEvent, 60000);
А очистить?)

2022-08-02 13:56 UTC, Stilwuc commented on src/pages/Posts.tsx
> +    const [fetchPosts, isPostsLoading, postError] = useFetching(async (pages) => {
`postError` не юзаешь (а мог бы)

2022-08-02 13:56 UTC, Stilwuc commented on src/utils/dateAndTime.ts
> +        time.getMinutes().toString().length === 1
Жесткое форматирование)
Тут дубли есть, можно было бы вынести  проверну на length = 1 и +0 в отдельную функцию.
А еще лучше подумать как сделать проще мб
Вот например
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

2022-08-02 13:56 UTC, Stilwuc commented on src/pages/Posts.tsx
> +    const [pages, setPages] = useState(0);
Немного смущало название переменной когда читал код, типо как будто здесь все страницы контента лежат, но пофакту просто текущая страница)
Так что лучше что то типо `currentPage` или `pageNumber`

2022-08-02 13:56 UTC, Stilwuc commented on src/API/PostService.ts
> +        return [].concat(...array);
Я так понял это ты хотел так ссылку новую сгенерить?
Лучше тогда так
```suggestion
        return [...array];
```
И ts ignore не нужен

2022-08-02 13:56 UTC, Stilwuc commented on src/API/PostService.ts
> +        for (let page = 1; page <= pages; page++) {
Лучше юзать функциональные forEach и тд, `for` и `while` такое)
Тут конкретно можно `new Array` длины `pages` и там уже forEach с индексом изи
Или еще лучше и map сразу сделать с Promise.all

2022-08-02 13:56 UTC, Stilwuc commented on src/pages/Posts.tsx
> +        setInterval(reloadEvent, 60000);
Авто релоад кста не работает, посдказка `posts.length` ;)

2022-08-02 13:56 UTC, Stilwuc commented on src/pages/PostIdPage.tsx
> +        // @ts-ignore
Ну тс игнор не надо что ты)
![image](https://user-images.githubusercontent.com/44724024/182383585-28a38150-5469-47aa-8f37-d20f2ee15ca7.png)

2022-08-02 13:56 UTC, Stilwuc commented on src/pages/PostIdPage.tsx
> +        return <></>;
можно null возвращать, это валидный jsx

2022-08-02 13:56 UTC, Stilwuc commented on src/pages/PostIdPage.tsx
> +    const [fetchPostById, isLoading, error] = useFetching(async (id) => {
error не юзаешь
типизацию аргументов не забывай

2022-08-02 13:56 UTC, Stilwuc commented on src/pages/PostIdPage.tsx
> +    ) : (
Такие большие тернарники не очень, лучше ранний выход из компонента

2022-08-02 13:56 UTC, Stilwuc commented on src/hooks/useObserver.ts
> +        observer.current = new IntersectionObserver(localCallback);
Солидно

2022-08-02 13:56 UTC, Stilwuc commented on src/components/Comment.tsx
> +                                        temporaryArray.push(<Comment comment={comm} key={comm.id}/>);
не стоит хранить в стейте jsx верстку без надобности, небольшой депотимайз.
Лучше хранить обычные данные, типо json и тд, поэтому тут просто comm и закидывай

2022-08-02 13:56 UTC, Stilwuc commented on src/components/Comment.tsx
> +                                    components.length = 0;
ой ой, опасно

2022-08-02 13:56 UTC, Stilwuc commented on src/components/Comment.tsx
> +                                    comment.comments.map((comm) => {
map возвращает новый массив, а ты его юзаешь как forEach который пушит каждый элемент в temp массив что и есть map)
вообщем вот так короче и правильней
```
  setComponents(comment.comments.map((comm) => <Comment comment={comm} key={comm.id}/>));
```

2022-08-02 13:56 UTC, Stilwuc commented on src/components/Comment.tsx
> +                    {components.map((component) => component)}
jsx массив можно просто так зарендерить
```suggestion
                    {components}
```

2022-08-02 13:56 UTC, Stilwuc commented on src/components/AppBar.tsx
> +    window?: () => Window;
Вроде не юзаешь нигде эту штуку

2022-08-02 13:57 UTC, Stilwuc commented
Вообщем гуд 👍 
Но пару вещей поправить надо)

2022-08-02 14:23 UTC, Chancellor-Arthur commented
Всё понял, огромное спасибо, сейчас поправлю

2022-08-02 14:46 UTC, Chancellor-Arthur commented on src/API/PostService.ts
> +        return [].concat(...array);
Ну тут не совсем так, я пытался превратить двумерный массив в одномерный, но уже нашел метод `flat()`, так что всё ок

2022-08-02 16:14 UTC, Chancellor-Arthur commented on src/API/PostService.ts
> +        for (let page = 1; page <= pages; page++) {
@Stilwuc тут случилось что-то страшное и я не понимаю что пошло не так
![image](https://user-images.githubusercontent.com/86954283/182422689-4b97761b-c314-4672-90f7-86b483b9f8e2.png)

2022-08-02 16:16 UTC, Chancellor-Arthur commented on src/API/PostService.ts
> +        for (let page = 1; page <= pages; page++) {
Вот так тоже плохо
![image](https://user-images.githubusercontent.com/86954283/182423196-5d39256c-3146-4068-ba72-14d608835d57.png)

2022-08-02 16:50 UTC, Chancellor-Arthur commented on src/API/PostService.ts
> +        for (let page = 1; page <= pages; page++) {
Ошибка та же
![image](https://user-images.githubusercontent.com/86954283/182430538-d6c3f805-a3a9-4dcc-9a63-b9af333fad48.png)

2022-08-02 17:00 UTC, Stilwuc commented on src/API/PostService.ts
> +        for (let page = 1; page <= pages; page++) {
Тут такая тема что ты делаешь асинковый итератор массива, но никто не await'ишь его, в текущей ситуации он у тебя этот код выполнится позже чем return.
Чтобы дождаться выполнения async итераций обычно используют такую конструкцию - 
```
await Promise.all(new Array(pages).map(async(_page, index) => {
   await ...
})
```
Типо у тебя сам итератор async, и каждую итерацию при помощи map мы будем возвращать промис одной итерации который надо заресолвить.
Ресолвить это все будет Promise.all, который полностью заресолвится только когда каждый элемент массива который мы закинули через map будет заресолвлен.
---

Но если что советую сразу избавится от лишнего const array с push и сделать так 
```
const array = await Promise.all(new Array(pages).map(async(_page, index) => {
   return await axios.get(...
})
```

И на финал останется убрать не нужный await внутри функции итератора, так как мы можем просто делать return промис который будет получаться при обычном axios.get и тем самым у нас при map как раз и будет массив из промисов

 ```
const array = await Promise.all(new Array(pages).map(async(_page, index) => {
   return axios.get(...
})
```

2022-08-02 17:39 UTC, Chancellor-Arthur commented on src/API/PostService.ts
> +        for (let page = 1; page <= pages; page++) {
@Stilwuc Всё шикарно, но оно не работает -_-
![image](https://user-images.githubusercontent.com/86954283/182438136-c200be3d-3616-4e6b-8aba-46fb13410d37.png)
Вернулся массив undefined, и что ещё интересно, api запрос не ушёл, как будто этой строки совсем нет

2022-08-02 17:58 UTC, Stilwuc commented on src/API/PostService.ts
> +        for (let page = 1; page <= pages; page++) {
Попался на ловушку new Array)
Тоже когда то там был
Вот reference по фиксу `new Array(pages).fill(undefined).map`
https://stackoverflow.com/a/35086350/11943409

2022-08-02 18:36 UTC, Chancellor-Arthur commented on src/pages/Posts.tsx
> +        setInterval(reloadEvent, 60000);
@Stilwuc `posts.length` убрал, а проблема никуда не делась, я правильно понимаю, что у меня значение замыкается?
![image](https://user-images.githubusercontent.com/86954283/182448652-ffdf7ddc-8066-4fe1-8eb7-e13d7cb26bca.png)

2022-08-02 18:55 UTC, Stilwuc commented on src/pages/Posts.tsx
> +        setInterval(reloadEvent, 60000);
Правильно понимаешь.
Есть идеи как фиксить?
Если нету маякуй

2022-08-02 19:21 UTC, Chancellor-Arthur commented on src/pages/Posts.tsx
> +        setInterval(reloadEvent, 60000);
@Stilwuc Идеи были, сейчас кончились, а проблема никуда не делась :(

2022-08-02 19:25 UTC, Chancellor-Arthur commented on src/pages/PostIdPage.tsx
> +    const [fetchPostById, isLoading, error] = useFetching(async (id) => {
@Stilwuc Есть ли способы типизировать ошибку рантайма как-то кроме `any`?
![image](https://user-images.githubusercontent.com/86954283/182456929-f31b34a2-96ad-44e9-aff3-8bed16843fc1.png)

2022-08-02 19:29 UTC, Chancellor-Arthur commented
@Stilwuc Заметил странную проблему, этот маршрут не работает, не происходит переадрисации, хотя та же самая строка в прошлом проекте работала, разница только в наличии ts
![image](https://user-images.githubusercontent.com/86954283/182457407-cd585819-7171-4d21-ad5c-64901d092e8b.png)

2022-08-02 19:32 UTC, Stilwuc commented on src/pages/PostIdPage.tsx
> +    const [fetchPostById, isLoading, error] = useFetching(async (id) => {
По умолчанию начиная с версии тс 4.4 что ли, она типизируется как unknown, и это правильно.
Ты должен работать с exception как с unknown типом, и проверять а является ли эта ошибка объектом, а есть ли у него поле message и тд. Так как ты твой try/catch и ты не можешь быть уверен какая именно тебе ошибка прилитит, будет ли она от аксиоса, или это просто null pointer.
Вот хорошая статья об этом, и как обрабатывать ошибки
https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript

2022-08-02 19:34 UTC, Stilwuc commented on src/pages/Posts.tsx
> +        setInterval(reloadEvent, 60000);
Ок, ну решение в лоб здесь сделать useEffect который будет выполняться не один раз на mount как у тебя, а каждый раз при изменении длинны массива (ну или на скрине currentPage).
Тогда у тебя будет всегда вызыватья актуальный listener, а старый чистится при помощи clearInterval

2022-08-02 19:49 UTC, Chancellor-Arthur commented
@Stilwuc, пожалуй, всё готово)

2022-08-03 09:50 UTC, Stilwuc approved these changes
Есть пару стилистических моментов (претиером бы пройтись, названия интерфейсов с I, названия переменных неочевидные), но это такое, не серьезные приколы.
Вообщем погнали мержить я считаю, все отлично и так, тут ты и mui покурил, и observervation намутил крч шик 👍 
(console.log только удали :D)

2022-08-03 09:50 UTC, Stilwuc commented on src/pages/Posts.tsx
> +        console.log(currentPage);
Забыл убрать

2022-08-03 09:50 UTC, Stilwuc commented on src/components/AppBar.tsx
> +    window?: () => Window;
Вроде все еще не юзаешь)

2022-08-03 09:50 UTC, Stilwuc commented on src/pages/PostIdPage.tsx
> +        return null;
А поч не `<Loader />`

2022-08-03 10:03 UTC, Chancellor-Arthur commented on src/pages/PostIdPage.tsx
> +        return null;
Интерфейс использую
![image](https://user-images.githubusercontent.com/86954283/182580949-e4a2907d-fdbc-4e5a-bc05-fcb6f1dc9db1.png)
По поводу почему не лоадер - это типо была обработка граничного случая, когда новость с сервера типо вернулась, но `undefined`. Лоадер показывается строкой ниже

2022-08-03 10:48 UTC, Stilwuc commented
@crutch12 

- [ ] merge check

2022-08-03 10:49 UTC, Chancellor-Arthur commented
@Stilwuc Костю зовём, или я мержу?

2022-08-03 15:23 UTC, crutch12 commented
Даня, тебе не надо меня звать, ты же сам оцениваешь

2022-08-03 15:32 UTC, Stilwuc commented
> Даня, тебе не надо меня звать, ты же сам оцениваешь

Понял принял)
@Chancellor-Arthur ну тогда запускай мерж

2022-08-03 15:37 UTC, Chancellor-Arthur commented
Есть, шеф:)

2022-08-03 15:37 UTC, merged